export enum NavigationActionsEnum {
  CREATE_IFD = 'CREATE_IFD',
  START_ESTIMATION = 'START_ESTIMATION',
  SUBMIT_ESTIMATION = 'SUBMIT_ESTIMATION',
  WAIT_ESTIMATION = 'WAIT_ESTIMATION',
  NEXT_ESTIMATION = 'NEXT_ESTIMATION',
  FINISH_ESTIMATION = 'FINISH_ESTIMATION'
}
