version: '3.8'
services:
  postgres:
    image: postgres:16-alpine3.20
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: estimates-application
    ports:
      - "5432:5432"
